= {lab_name}

++++
<br>
<h4><i>Red Hat AI Development Roadshow - Platform Engineer Track</i></h4>
<br>
<style>
  .nav-container, .pagination, .toolbar {
    display: none !important;
  }
  .doc {
    max-width: 70rem !important;
  }
</style>
++++

Meet Raj, a platform engineer at Parasol, specializing in streamlining AI workflows. In his latest assignment, he's tasked with enhancing the productivity of his team and is evaluating Red Hat’s internal developer portal and tooling. By doing so, he aims to reduce the cognitive load for AI workloads, enabling faster development cycles and more efficient collaboration among team members.

Raj is also responsible for constructing software templates that effectively integrate IT policies and incorporate both off-the-shelf and custom AI models. This will allow his organization to maintain a consistent approach while ensuring compliance with security standards and fostering innovation through reusable components.

Additionally, Raj’s responsibilities include managing pipelines for automating the entire process of building, securing (signing/attestation), and deploying AI models and applications to production platforms. This not only saves the developer’s time but also ensures a more consistent deployment process with improved security features. Furthermore, he needs to observe and optimize the performance of custom AI models in production, as well as securely and automatically scale AI models and apps across clusters to meet the demands of the business.



== Get started

Modules are provisioned on demand by you by using the *Workshop Deployer*.

Your access details to the lab:

* Access *Workshop Deployer* by  https://workshop-deployer.{openshift_subdomain}[clicking here^, window="workshopdeployer"]
* Username: *{user_name}*
* Password: *{user_password}*

Before diving into a particular module, we recommend that you go through the workshop introduction module, to explore the technical and functional environment for this workshop. *Go ahead! Choose your adventure!*