= Using Internal Developer Portals for AI Application Developers
:imagesdir: ../assets/images
:sectnums:

++++
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3HTRSDJ3M4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-3HTRSDJ3M4');
</script>
++++

== Goals of this lab

In this exercise, as a Platform Engineer and will learn how to leverage Red Hat's internal developer portal and tooling to enhance team productivity and reduce developer cognitive load for AI workloads. This exercise will guide you through creating compelling and useful software templates that your developers can use which encapsulates IT policies and incorporates both off-the-shelf and custom AI models. You will start by creating a new AI model template using a sample application. Next, you'll use OpenShift AI to install and configure the LLM, such as IBM Granite, referenced by the template. Following this, you will deploy the sample application using the AI model template in Developer Hub Hub and verify its functionality after the CI/CD process completes. Additionally, you have the option to add a policy exception temporarily in Dev Hub to waive a potential vulnerability in the AI app. This hands-on exercise aims to equip you with the skills to streamline AI workflows, ensuring compliance while fostering innovation through reusable components.

== Run podman desktop

Introduction to gen AI + discover and experiment with gen AI models and AI applications on the local desktop, in an inner loop

== TBD

=== TBD

== Start a playground, chat with it

== Kill playground, try text summarization recipe, upload claim PDF, view summarization

== Open summarization app (python) in vscode, inspect code (briefly)

== Change the prompt, restart, and observe changes.

== Conclusion

We hope you have enjoyed this module!

Here is a quick summary of what we have learned:

- TBD
- TBD
- TBD