= Scaling models
:imagesdir: ../assets/images
:sectnums:

++++
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-3HTRSDJ3M4"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-3HTRSDJ3M4');
</script>
++++

== Goals of this lab

The goal of this lab is to learn how to securely and automatically scale AI models and apps across clusters - **more detail needed**.

== Run podman desktop

Introduction to gen AI + discover and experiment with gen AI models and AI applications on the local desktop, in an inner loop

== TBD

=== TBD

== Start a playground, chat with it

== Kill playground, try text summarization recipe, upload claim PDF, view summarization

== Open summarization app (python) in vscode, inspect code (briefly)

== Change the prompt, restart, and observe changes.

== Conclusion

We hope you have enjoyed this module!

Here is a quick summary of what we have learned:

- TBD
- TBD
- TBD